let colours = [
    { number: 0, place: "New Zealand", background: "#a1fffe", material: "Tree", dyeing: true, weaving: false, painting: false, image1:"https://source.unsplash.com/ndN00KmbJ1c", image2:"../img/landing_bg.jpg", image3:"https://source.unsplash.com/ndN00KmbJ1c"},
    { number: 1, place: "New Zealand", background: "#a1fffe", material: "Earth", dyeing: false, weaving: false, painting: true, image1:"../img/landing_bg.jpg", image2:"../img/landing_bg.jpg", image3:"https://source.unsplash.com/ndN00KmbJ1c"},
    { number: 2, place: "Taiwan", background: "#a1fffe", material: "Tree", dyeing: false, weaving: true, painting: false, image1:"https://source.unsplash.com/ndN00KmbJ1c", image2:"../img/landing_bg.jpg", image3:"https://source.unsplash.com/ndN00KmbJ1c"},
    { number: 3, place: "Taiwan", background: "#a1fffe", material: "Earth", dyeing: false, weaving: false, painting: true,  image1:"https://source.unsplash.com/ndN00KmbJ1c", image2:"../img/landing_bg.jpg", image3:"https://source.unsplash.com/ndN00KmbJ1c"},
    { number: 4, place: "California", background: "#d3c7f3", material: "Grass", dyeing: false, weaving: true, painting: false, image1:"https://source.unsplash.com/ndN00KmbJ1c", image2:"https://source.unsplash.com/ndN00KmbJ1c", image3:"https://source.unsplash.com/ndN00KmbJ1c"},
    { number: 5, place: "California", background: "#faffb8", material: "Tree", dyeing: false, weaving: true, painting: true,  image1:"https://source.unsplash.com/ndN00KmbJ1c", image2:"https://source.unsplash.com/ndN00KmbJ1c", image3:"https://source.unsplash.com/ndN00KmbJ1c"},
    { number: 6, place: "Italy", background: "#faffb8", material: "Earth", dyeing: true, weaving: false, painting: false,  image1:"https://source.unsplash.com/ndN00KmbJ1c", image2:"https://source.unsplash.com/ndN00KmbJ1c", image3:"https://source.unsplash.com/ndN00KmbJ1c"}, 

  ];