let colours = [
    { number: 0, 
      place: "Italy", 
      background: "#ffffff", 
      material: "Earth", 
      dyeing: false, 
      weaving: false, 
      painting: true, 
      gardening: false,
      cooking: false,    
      thumb: "/img/arc/1/thumb.jpg",  
      images:[
        {src: "/img/arc/1/1.jpg", caption: ""},
        {src: "/img/arc/1/2.jpg", caption: ""},
        {src: "/img/arc/1/3.jpg", caption: ""},
        {src: "/img/arc/1/4.jpg", caption: ""},
        {src: "/img/arc/1/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        {image: "/img/arc/1/proj1.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "A rich red/brown clay from Southern Italy",
      description: "A rich red clay gathered from under a fig tree in Puglia, Italy. Gathered as we went to the beach on a hot summer's day on a trip uniting friends from all over the world. I kept thinking of the story of Prometheus blowing sculpting humans from Greek myth and wondering if this is the same clay the stories talk about. H."
    },


    { number: 1, 
      place: "Italy", 
      background: "#ffffff", 
      material: "Earth", 
      dyeing: false, 
      weaving: false, 
      painting: true, 
      gardening: false,
      cooking: false,      
      thumb: "/img/arc/2/thumb.jpg",  
      images:[
        {src: "/img/arc/2/1.jpg", caption: ""},
        {src: "/img/arc/2/2.jpg", caption: ""},
        {src: "/img/arc/2/3.jpg", caption: ""},
        {src: "/img/arc/2/4.jpg", caption: ""},
        {src: "/img/arc/2/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        {image: "/img/arc/2/proj1.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "Standing in stark contrast the the dark red clay all around, we found this soft yellow colour with stones mixed through it alongside the road. Made up from tiny particles, in mixed very nicely into a soft plasticine.",
    },
    
    { number: 2, 
      place: "Taiwan", 
      background: "#ffffff", 
      material: "Plant", 
      dyeing: false, 
      weaving: true, 
      painting: false, 
      gardening: false,
      cooking: false,     
      thumb: "/img/arc/3/thumb.jpg",   
      images:[
        {src: "/img/arc/3/1.jpg", caption: ""},
        {src: "/img/arc/3/2.jpg", caption: ""},
        {src: "/img/arc/3/3.jpg", caption: ""},
        {src: "/img/arc/3/4.jpg", caption: ""},
        {src: "/img/arc/3/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        {image: "/img/arc/3/proj1.jpg", name: "Weaving", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "Rush grass grown and woven in Miaoli, Taiwan on a training course at Lin Rush Weaving. Memorising the complex patterns of movement to align all the grass fibers just right took many many hours of hunched over practice.",
    },

    { number: 3, 
      place: "New Zealand", 
      background: "#ffffff", 
      material: "Earth", 
      dyeing: false, 
      weaving: false, 
      painting: true, 
      gardening: false,
      cooking: false,   
      thumb: "/img/arc/4/thumb.jpg",      
      images:[
        {src: "/img/arc/16/1.jpg", caption: ""},
        {src: "/img/arc/16/2.jpg", caption: ""},
        {src: "/img/arc/16/3.jpg", caption: ""},
        {src: "/img/arc/16/4.jpg", caption: ""},
        {src: "/img/arc/16/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        {image: "/img/arc/16/proj1.jpg", name: "Ceramics", caption: ""}, 
        {image: "/img/arc/16/proj2.jpg", name: "Painting", caption: ""}, 
        {image: "/img/arc/16/proj3.jpg", name: "Fabric Dying", caption: ""}, 
        {image: "/img/arc/16/proj4.jpg", name: "Dying", caption: ""},  
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "Gathered from a creek bed as the clay ran down the slope and settled into pools alongside the creek. It formed a ceramic clay with excellent plasticity for some basic coil formed pottery.",
    },

    { number: 4, 
      place: "Taiwan", 
      background: "#ffffff", 
      material: "Tree", 
      dyeing: false, 
      weaving: false, 
      painting: false, 
      gardening: false,
      cooking: false,   
      thumb: "/img/arc/5/thumb.jpg",           
      images:[
        {src: "/img/arc/5/1.jpg", caption: ""},
        {src: "/img/arc/5/2.jpg", caption: ""},
        {src: "/img/arc/5/3.jpg", caption: ""},
        {src: "/img/arc/5/4.jpg", caption: ""},
        // {src: "/img/arc/5/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        // {image: "/img/arc/5/proj1.jpg", name: "Weaving", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "Paper pulp in a paper mill in Puli, incredible the fine texture of the fibres that are created from the processing of the bark into the paper pulp, and the tight interlocking network it forms when pulled.",
    },

    { number: 5, 
      place: "New Zealand", 
      background: "#ffffff", 
      material: "Tree", 
      dyeing: false, 
      weaving: false, 
      painting: false, 
      gardening: false,
      cooking: false,      
      thumb: "/img/arc/6/thumb.jpg",        
      images:[
        {src: "/img/arc/6/1.jpg", caption: ""},
        {src: "/img/arc/6/2.jpg", caption: ""},
        {src: "/img/arc/6/3.jpg", caption: ""},
        {src: "/img/arc/6/4.jpg", caption: ""},
        {src: "/img/arc/6/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        {image: "/img/arc/6/proj1.jpg", name: "Papermaking", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "Our first papermaking attempt with some fallen birch trees we beat and mashed into a fibrous pulp, the result was very felt-like as we didn't really get the fibres treated fully, but a pretty good first attempt.",
    },

    { number: 6, 
      place: "New Zealand", 
      background: "#ffffff", 
      material: "Earth", 
      dyeing: true, 
      weaving: false, 
      painting: true, 
      gardening: false,
      cooking: false,    
      thumb: "/img/arc/7/thumb.jpg",          
      images:[
        {src: "/img/arc/7/1.jpg", caption: ""},
        {src: "/img/arc/7/2.jpg", caption: ""},
        // {src: "/img/arc/6/3.jpg", caption: ""},
        // {src: "/img/arc/6/4.jpg", caption: ""},
        // {src: "/img/arc/6/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        {image: "/img/arc/7/proj1.jpg", name: "Fabric Dying", caption: ""}, 
        {image: "/img/arc/7/proj2.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "A pink/red soft sandy clay mix pulled from the side of the road in Riverhead, the clay needed a lot of processing to form fine particles for painting, but gave a really nice textured finish.",
    },

    { number: 7, 
      place: "California", 
      background: "#ffffff", 
      material: "Fungi", 
      dyeing: true, 
      weaving: false, 
      painting: false, 
      gardening: false,
      cooking: false,      
      thumb: "/img/arc/8/thumb.jpg",        
      images:[
        {src: "/img/arc/8/1.jpg", caption: ""},
        {src: "/img/arc/8/2.jpg", caption: ""},
        {src: "/img/arc/8/3.jpg", caption: ""},
        // {src: "/img/arc/6/4.jpg", caption: ""},
        // {src: "/img/arc/6/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        // {image: "/img/arc/7/proj1.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/arc/7/proj2.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "A full spectrum of colour created from various funghi and lichen sources at a workshop by Alissa Allen. Incredible the range of colours able to be created and dyed into woolen bundles.",
    },

    { number: 8, 
      place: "New Zealand", 
      background: "#ffffff", 
      material: "Earth", 
      dyeing: false, 
      weaving: false, 
      painting: true, 
      gardening: false,
      cooking: false,      
      thumb: "/img/arc/9/thumb.jpg",        
      images:[
        {src: "/img/arc/9/1.jpg", caption: ""},
        {src: "/img/arc/9/2.jpg", caption: ""},
        {src: "/img/arc/9/3.jpg", caption: ""},
        // {src: "/img/arc/6/4.jpg", caption: ""},
        // {src: "/img/arc/6/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        {image: "/img/arc/9/proj1.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/arc/7/proj2.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "An ultra fine white and slighly iridescent white clay found at a building site, slight texture with the large particles present but painted onto watercolour paper pleasantly.",
    },

    { number: 9, 
      place: "New Zealand", 
      background: "#ffffff", 
      material: "Tree", 
      dyeing: true, 
      weaving: false, 
      painting: false, 
      gardening: false,
      cooking: false,      
      thumb: "/img/arc/10/thumb.jpg",        
      images:[
        {src: "/img/arc/10/1.jpg", caption: ""},
        {src: "/img/arc/10/2.jpg", caption: ""},
        {src: "/img/arc/10/3.jpg", caption: ""},
        // {src: "/img/arc/6/4.jpg", caption: ""},
        // {src: "/img/arc/6/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        {image: "/img/arc/10/proj1.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/arc/7/proj2.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "Fabric dying experiments with Tanekaha tree in New Zealand, pre-treating with various mordants to experiment with colour shifts. Dyed into cotton, which faded into these colours after a wash.",
    },

    { number: 10, 
      place: "California", 
      background: "#ffffff", 
      material: "Plant", 
      dyeing: false, 
      weaving: false, 
      painting: false, 
      gardening: true,
      cooking: false,      
      thumb: "/img/arc/11/thumb.jpg",        
      images:[
        {src: "/img/arc/11/1.jpg", caption: ""},
        {src: "/img/arc/11/2.jpg", caption: ""},
        {src: "/img/arc/11/3.jpg", caption: ""},
        // {src: "/img/arc/6/4.jpg", caption: ""},
        // {src: "/img/arc/6/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        // {image: "/img/arc/10/proj1.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/arc/7/proj2.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "Loofa gourds grown in the backyard and left to dry, then peeled to reveal a dense cell network and loofa structure we are all familiar with",
    },

    { number: 11, 
      place: "California", 
      background: "#ffffff", 
      material: "Fungi", 
      dyeing: false, 
      weaving: false, 
      painting: false, 
      gardening: false,
      cooking: true,      
      thumb: "/img/arc/12/thumb.jpg",        
      images:[
        {src: "/img/arc/12/1.jpg", caption: ""},
        {src: "/img/arc/12/2.jpg", caption: ""},
        {src: "/img/arc/12/3.jpg", caption: ""},
        {src: "/img/arc/12/4.jpg", caption: ""},
        // {src: "/img/arc/6/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        // {image: "/img/arc/10/proj1.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/arc/7/proj2.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "Porcini mushrooms foraged on the California coast. The colour is so close to the surrounding earth and ground debris, but also so distinct. The eyes become trained to identify the particular orange red colour amongst the forest floor.",
    },

    { number: 12, 
      place: "California", 
      background: "#ffffff", 
      material: "Plant", 
      dyeing: false, 
      weaving: false, 
      painting: false, 
      gardening: true,
      cooking: false,      
      thumb: "/img/arc/13/thumb.jpg",        
      images:[
        {src: "/img/arc/13/1.jpg", caption: ""},
        {src: "/img/arc/13/2.jpg", caption: ""},
        {src: "/img/arc/13/3.jpg", caption: ""},
        {src: "/img/arc/13/4.jpg", caption: ""},
        {src: "/img/arc/13/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        // {image: "/img/arc/10/proj1.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/arc/7/proj2.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "Peach and crimson coloured roses grown and enjoyed in the backyard, started our love of growing flowers and not just edibles.",
    },

    { number: 13, 
      place: "California", 
      background: "#ffffff", 
      material: "Plant", 
      dyeing: false, 
      weaving: true, 
      painting: false, 
      gardening: false,
      cooking: false,      
      thumb: "/img/arc/14/thumb.jpg",        
      images:[
        {src: "/img/arc/14/1.jpg", caption: ""},
        {src: "/img/arc/14/2.jpg", caption: ""},
        {src: "/img/arc/14/3.jpg", caption: ""},
        // {src: "/img/arc/13/4.jpg", caption: ""},
        // {src: "/img/arc/13/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        // {image: "/img/arc/10/proj1.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/arc/7/proj2.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "Rattan weaving self taught as a covid lockdown passtime, my entry into weaving as a practice as a birdge between my wheelhouse of woodworking and moving into more traditional fibre-arts. - H",
    },

    { number: 14, 
      place: "California", 
      background: "#ffffff", 
      material: "Plant", 
      dyeing: false, 
      weaving: false, 
      painting: false, 
      gardening: false,
      cooking: false,      
      thumb: "/img/arc/15/thumb.jpg",        
      images:[
        {src: "/img/arc/15/1.jpg", caption: ""},
        {src: "/img/arc/15/2.jpg", caption: ""},
        {src: "/img/arc/15/3.jpg", caption: ""},
        // {src: "/img/arc/13/4.jpg", caption: ""},
        // {src: "/img/arc/13/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        // {image: "/img/arc/10/proj1.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/arc/7/proj2.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "A favorite of mine to grow, sunflowers will forever make me smile. - H",
    },

    // { number: 15, 
    //   place: "New Zealand", 
    //   background: "#ffffff", 
    //   material: "Earth", 
    //   dyeing: false, 
    //   weaving: false, 
    //   painting: false, 
    //   gardening: false,
    //   cooking: false,      
    //   thumb: "/img/arc/16/thumb.jpg",        
    //   images:[
    //     {src: "/img/arc/16/1.jpg", caption: ""},
    //     {src: "/img/arc/16/2.jpg", caption: ""},
    //     {src: "/img/arc/16/3.jpg", caption: ""},
    //     {src: "/img/arc/16/4.jpg", caption: ""},
    //     {src: "/img/arc/16/5.jpg", caption: ""},
    //     // {src: "/img/arc/1/6.jpg", caption: ""},
    //   ],
    //   projects:[
    //     {image: "/img/arc/16/proj1.jpg", name: "Ceramics", caption: ""}, 
    //     {image: "/img/arc/16/proj2.jpg", name: "Painting", caption: ""}, 
    //     {image: "/img/arc/16/proj3.jpg", name: "Fabric Dying", caption: ""}, 
    //     {image: "/img/arc/16/proj4.jpg", name: "Dying", caption: ""},  
    //     // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
    //   ],
    //   link: {text: "", src: ""},
    //   highlight: "",
    //   description: "",
    // },

    { number: 15, 
      place: "New Zealand", 
      background: "#ffffff", 
      material: "Earth", 
      dyeing: true, 
      weaving: false, 
      painting: true, 
      gardening: false,
      cooking: false,       
      thumb: "/img/arc/17/thumb.jpg",        
      images:[
        {src: "/img/arc/17/1.jpg", caption: ""},
        {src: "/img/arc/17/2.jpg", caption: ""},
        {src: "/img/arc/17/3.jpg", caption: ""},
        {src: "/img/arc/17/4.jpg", caption: ""},
        // {src: "/img/arc/16/5.jpg", caption: ""},
        // {src: "/img/arc/1/6.jpg", caption: ""},
      ],
      projects:[
        {image: "/img/arc/17/proj1.jpg", name: "Fabric Dying", caption: ""}, 
        {image: "/img/arc/17/proj2.jpg", name: "Painting", caption: ""}, 
        // {image: "/img/arc/16/proj3.jpg", name: "Fabric Dying", caption: ""}, 
        // {image: "/img/arc/16/proj4.jpg", name: "Dying", caption: ""},  
        // {image: "/img/landing_bg.jpg", name: "Fabric Dying", caption: ""}
      ],
      link: {text: "", src: ""},
      highlight: "",
      description: "Deep red clay gathered from Mt Eden in Auckland, one of many ancient and dormany volcanic sites in the Auckland region. This interesting soil feels very volcanice, rough and gritty. It required a lot of grinding to form a smooth painting medium.",
    },

  ];